/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SponsorAdRequest } from '../../models/sponsor-ad-request';
import { SponsorAdResponse } from '../../models/sponsor-ad-response';

export interface UpdateSponsorAd$Params {
  adId: number;
      body?: {
'request': SponsorAdRequest;
'image'?: Blob;
}
}

export function updateSponsorAd(http: HttpClient, rootUrl: string, params: UpdateSponsorAd$Params, context?: HttpContext): Observable<StrictHttpResponse<SponsorAdResponse>> {
  const rb = new RequestBuilder(rootUrl, updateSponsorAd.PATH, 'put');
  if (params) {
    rb.path('adId', params.adId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SponsorAdResponse>;
    })
  );
}

updateSponsorAd.PATH = '/sponsorAd/updateAd/{adId}';
