/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Pageable } from './models/pageable';
export type { PageResponseProvidershipResponse } from './models/page-response-providership-response';
export type { PageResponseSponsorAdResponse } from './models/page-response-sponsor-ad-response';
export type { PageResponseSponsorOfferResponse } from './models/page-response-sponsor-offer-response';
export type { PageResponseSponsorshipResponse } from './models/page-response-sponsorship-response';
export type { PageResponseSupplierOfferResponse } from './models/page-response-supplier-offer-response';
export type { PageResponseSupplierTransactionResponse } from './models/page-response-supplier-transaction-response';
export type { PageResponseUserResponse } from './models/page-response-user-response';
export type { ProvidershipLightResponse } from './models/providership-light-response';
export type { ProvidershipMultipartRequest } from './models/providership-multipart-request';
export type { ProvidershipResponse } from './models/providership-response';
export type { SponsorAdMultipartRequest } from './models/sponsor-ad-multipart-request';
export type { SponsorAdResponse } from './models/sponsor-ad-response';
export type { SponsorOfferMultipartRequest } from './models/sponsor-offer-multipart-request';
export type { SponsorOfferResponse } from './models/sponsor-offer-response';
export type { SponsorshipLightResponse } from './models/sponsorship-light-response';
export type { SponsorshipLightsResponse } from './models/sponsorship-lights-response';
export type { SponsorshipPatchMultipartRequest } from './models/sponsorship-patch-multipart-request';
export type { SponsorshipResponse } from './models/sponsorship-response';
export type { SupplierOfferMultipartRequest } from './models/supplier-offer-multipart-request';
export type { SupplierOfferResponse } from './models/supplier-offer-response';
export type { SupplierTransactionLightResponse } from './models/supplier-transaction-light-response';
export type { SupplierTransactionMultipartRequest } from './models/supplier-transaction-multipart-request';
export type { SupplierTransactionResponse } from './models/supplier-transaction-response';
export type { User } from './models/user';
export type { UserResponse } from './models/user-response';
export type { UserUpdateRequest } from './models/user-update-request';
