/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseSponsorshipResponse } from '../../models/page-response-sponsorship-response';

export interface GetSponsorshipsByStatus$Params {
  status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'FINISHED';
  page?: number;
  size?: number;
}

export function getSponsorshipsByStatus(http: HttpClient, rootUrl: string, params: GetSponsorshipsByStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseSponsorshipResponse>> {
  const rb = new RequestBuilder(rootUrl, getSponsorshipsByStatus.PATH, 'get');
  if (params) {
    rb.path('status', params.status, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseSponsorshipResponse>;
    })
  );
}

getSponsorshipsByStatus.PATH = '/sponsorships/status/{status}';
