/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SponsorshipResponse } from '../../models/sponsorship-response';

export interface GetSponsorshipById$Params {
  sponsorshipId: number;
}

export function getSponsorshipById(http: HttpClient, rootUrl: string, params: GetSponsorshipById$Params, context?: HttpContext): Observable<StrictHttpResponse<SponsorshipResponse>> {
  const rb = new RequestBuilder(rootUrl, getSponsorshipById.PATH, 'get');
  if (params) {
    rb.path('sponsorshipId', params.sponsorshipId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SponsorshipResponse>;
    })
  );
}

getSponsorshipById.PATH = '/sponsorships/{sponsorshipId}';
