/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SponsorshipPatchMultipartRequest } from '../../models/sponsorship-patch-multipart-request';
import { SponsorshipResponse } from '../../models/sponsorship-response';

export interface PatchSponsorship$Params {
  sponsorshipId: number;
      body?: SponsorshipPatchMultipartRequest
}

export function patchSponsorship(http: HttpClient, rootUrl: string, params: PatchSponsorship$Params, context?: HttpContext): Observable<StrictHttpResponse<SponsorshipResponse>> {
  const rb = new RequestBuilder(rootUrl, patchSponsorship.PATH, 'patch');
  if (params) {
    rb.path('sponsorshipId', params.sponsorshipId, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SponsorshipResponse>;
    })
  );
}

patchSponsorship.PATH = '/sponsorships/{sponsorshipId}/status';
