/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface UpdateSponsorshipStatus$Params {
  sponsorshipId: number;
  newStatus: 'PENDING' | 'APPROVED' | 'REJECTED' | 'FINISHED';
}

export function updateSponsorshipStatus(http: HttpClient, rootUrl: string, params: UpdateSponsorshipStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, updateSponsorshipStatus.PATH, 'patch');
  if (params) {
    rb.path('sponsorshipId', params.sponsorshipId, {});
    rb.query('newStatus', params.newStatus, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

updateSponsorshipStatus.PATH = '/sponsorships/{sponsorshipId}/status';
