/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SponsorAdResponse } from '../models/sponsor-ad-response';
export interface PageResponseSponsorAdResponse {
  content?: Array<SponsorAdResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
