/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProvidershipLightResponse {
  bonusEarned?: number;
  createdDate?: string;
  hasPrintMachine?: boolean;
  id?: number;
  lastModifiedDate?: string;
  location?: string;
  producedProduct?: number;
  proofDocs?: Array<string>;
  providershipApprovalStatus?: 'PENDING' | 'APPROVED' | 'REJECTED';
  status?: 'PENDING' | 'DESIGNING_CUP' | 'PRODUCING_CUP' | 'PRODUCING_AND_SELLING' | 'SELLING' | 'COMPLETED';
  totalProduct?: number;
  userId?: string;
}
