/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Sponsorship } from '../models/sponsorship';
export interface Providership {
  bonusEarned?: number;
  createdBy?: string;
  createdDate?: string;
  hasPrintMachine?: boolean;
  id?: number;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  location?: string;
  producedProduct?: number;
  proofDocs?: Array<string>;
  providershipApprovalStatus?: 'PENDING' | 'APPROVED' | 'REJECTED';
  sponsorship?: Sponsorship;
  status?: 'PENDING' | 'DESIGNING_CUP' | 'PRODUCING_CUP' | 'PRODUCING_AND_SELLING' | 'SELLING' | 'COMPLETED';
  totalProduct?: number;
  userId?: string;
}
