/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SponsorshipLightResponse } from '../models/sponsorship-light-response';

/**
 * Response object containing providership data
 */
export interface ProvidershipResponse {

  /**
   * Bonus earned
   */
  bonusEarned?: number;

  /**
   * Creation timestamp
   */
  createdDate?: string;

  /**
   * Whether provider owns a print machine
   */
  hasPrintMachine?: boolean;

  /**
   * Providership ID
   */
  id?: number;

  /**
   * Last update timestamp
   */
  lastModifiedDate?: string;

  /**
   * Provider location
   */
  location?: string;

  /**
   * Number of products produced
   */
  producedProduct?: number;

  /**
   * Proof document URLs
   */
  proofDocs?: Array<string>;

  /**
   * Admin approval status
   */
  providershipApprovalStatus?: 'PENDING' | 'APPROVED' | 'REJECTED';

  /**
   * Associated sponsorship details
   */
  sponsorship?: SponsorshipLightResponse;

  /**
   * Providership status
   */
  status?: 'PENDING' | 'DESIGNING' | 'PRODUCING' | 'PRODUCING_AND_SELLING' | 'SELLING' | 'COMPLETED';

  /**
   * Total number of products to be produced
   */
  totalProduct?: number;

  /**
   * User ID of the provider
   */
  userId?: string;
}
