/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProvidershipRequest {
  bonusEarned?: number;
  hasPrintMachine: boolean;
  location: string;
  producedProduct?: number;
  providedProductTypes: Array<'CUPS' | 'BAGS' | 'SHIRTS' | 'STICKERS' | 'SUGAR_PACKS' | 'NOTES' | 'BALLS' | 'Bottles'>;
  providershipApprovalStatus?: 'PENDING' | 'APPROVED' | 'REJECTED';
  sponsorshipId?: number;
  status?: 'PENDING' | 'DESIGNING' | 'PRODUCING' | 'PRODUCING_AND_SELLING' | 'SELLING' | 'COMPLETED';
  totalProduct?: number;
  userId?: string;
}
