/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProvidershipRequest {
  bonusEarned: number;
  hasPrintMachine: boolean;
  location: string;
  producedProduct: number;
  providershipApprovalStatus: 'PENDING' | 'APPROVED' | 'REJECTED';
  sponsorshipId: number;
  status: 'PENDING' | 'DESIGNING_CUP' | 'PRODUCING_CUP' | 'PRODUCING_AND_SELLING' | 'SELLING' | 'COMPLETED';
  totalProduct: number;
  userId: string;
}
