/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SponsorAdResponse {
  content?: string;
  design?: string;
  designColors?: Array<string>;
  placement?: string;
  title?: string;
}
