/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Sponsorship } from '../models/sponsorship';
import { SupplierOffer } from '../models/supplier-offer';
export interface SponsorAd {
  content?: string;
  createdBy?: string;
  createdDate?: string;
  design?: string;
  design_colors?: Array<string>;
  id?: number;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  placement?: string;
  sponsorships?: Array<Sponsorship>;
  supplierOffers?: Array<SupplierOffer>;
  title?: string;
  userId?: string;
}
