/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SponsorOfferRequest {
  category: string;
  description: string;
  numberAds: number;
  price: number;
  productQuantity: number;
  productType: string;
  salesArea: string;
  status: 'COMING_SOON' | 'AVAILABLE' | 'CLOSED';
  title: string;
}
