/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SponsorAdResponse } from '../models/sponsor-ad-response';
import { SponsorOfferResponse } from '../models/sponsor-offer-response';
import { SupplierTransactionResponse } from '../models/supplier-transaction-response';
export interface SponsorshipLightResponse {
  createdDate?: string;
  id?: number;
  sponsorAds?: Array<SponsorAdResponse>;
  sponsorOffer?: SponsorOfferResponse;
  status?: 'PENDING' | 'APPROVED' | 'REJECTED' | 'FINISHED';
  supplierTransactions?: Array<SupplierTransactionResponse>;
  userId?: string;
}
