/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SponsorOfferResponse {
  category?: string;
  description?: string;
  explainImages?: Array<string>;
  id?: number;
  numberAds?: number;
  price?: number;
  productQuantity?: number;
  productType?: string;
  salesArea?: string;
  status?: string;
  title?: string;
}
