/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Sponsorship } from '../models/sponsorship';
export interface SponsorOffer {
  category?: string;
  createdBy?: string;
  createdDate?: string;
  description?: string;
  explainImages?: Array<string>;
  id?: number;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  numberAds?: number;
  price?: number;
  productQuantity?: number;
  productType?: string;
  salesArea?: string;
  sponsorships?: Array<Sponsorship>;
  status?: 'COMING_SOON' | 'AVAILABLE' | 'CLOSED';
  title?: string;
  userId?: string;
}
