/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Multipart form request for sponsor offer
 */
export interface SponsorOfferMultipartRequest {

  /**
   * List of images
   */
  explainImages?: Array<Blob>;

  /**
   * Sponsor Offer JSON string
   */
  request?: string;
}
