/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Multipart form request for sponsor ad
 */
export interface SponsorAdMultipartRequest {

  /**
   * Image file
   */
  image?: Blob;

  /**
   * Sponsor Ad JSON string
   */
  request?: string;
}
