/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Providership } from '../models/providership';
import { SponsorAd } from '../models/sponsor-ad';
import { SponsorOffer } from '../models/sponsor-offer';
import { SupplierTransaction } from '../models/supplier-transaction';
export interface Sponsorship {
  createdBy?: string;
  createdDate?: string;
  id?: number;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  providerships?: Array<Providership>;
  sponsorAds?: Array<SponsorAd>;
  sponsorOffer?: SponsorOffer;
  status?: 'PENDING' | 'APPROVED' | 'REJECTED' | 'FINISHED';
  supplierTransactions?: Array<SupplierTransaction>;
  userId?: string;
}
