/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProvidershipResponse } from '../models/providership-response';
import { SponsorAdResponse } from '../models/sponsor-ad-response';
import { SponsorOfferResponse } from '../models/sponsor-offer-response';
export interface SponsorshipLightsResponse {
  createdDate?: string;
  id?: number;
  providerships?: Array<ProvidershipResponse>;
  sponsorAds?: Array<SponsorAdResponse>;
  sponsorOffer?: SponsorOfferResponse;
  status?: 'PENDING' | 'APPROVED' | 'REJECTED' | 'FINISHED';
  userId?: string;
}
