/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SupplierOfferResponse } from '../models/supplier-offer-response';
export interface SupplierTransactionLightResponse {
  id?: number;
  percentage?: number;
  proofs?: Array<string>;
  quantitySold?: number;
  relativePrice?: number;
  supplierOffer?: SupplierOfferResponse;
  supplierTransactionStatus?: 'PENDING' | 'APPROVED' | 'REJECTED' | 'FINISHED' | 'COMPLETED';
  userId?: string;
}
