/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Sponsorship } from '../models/sponsorship';
import { SupplierOffer } from '../models/supplier-offer';
export interface SupplierTransaction {
  createdBy?: string;
  createdDate?: string;
  discount?: number;
  id?: number;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  locations?: Array<string>;
  percentage?: number;
  proofs?: Array<string>;
  quantitySold?: number;
  relativePrice?: number;
  sponsorship?: Sponsorship;
  supplierOffer?: SupplierOffer;
  supplierTransactionStatus?: 'PENDING' | 'APPROVED' | 'REJECTED' | 'FINISHED' | 'COMPLETED';
  userId?: string;
}
