/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SupplierOfferRequest {
  description: string;
  endDate: string;
  price: number;
  quantityAvailable: number;
  sponsorAdIds?: Array<number>;
  startDate: string;
  status: 'COMING_SOON' | 'AVAILABLE' | 'CLOSED';
  title: string;
}
