/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SupplierTransactionUpdateRequest {
  locations: Array<string>;
  quantitySold: number;
  status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'FINISHED' | 'COMPLETED';
}
