/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SponsorshipLightsResponse } from '../models/sponsorship-lights-response';
import { SupplierOfferResponse } from '../models/supplier-offer-response';
export interface SupplierTransactionResponse {
  id?: number;
  locations?: Array<string>;
  percentage?: number;
  proofs?: Array<string>;
  quantitySold?: number;
  relativePrice?: number;
  sponsorship?: SponsorshipLightsResponse;
  supplierOffer?: SupplierOfferResponse;
  supplierTransactionStatus?: 'PENDING' | 'APPROVED' | 'REJECTED' | 'FINISHED' | 'COMPLETED';
  userId?: string;
}
