/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SponsorAd } from '../models/sponsor-ad';
import { SupplierTransaction } from '../models/supplier-transaction';
export interface SupplierOffer {
  createdBy?: string;
  createdDate?: string;
  description?: string;
  endDate?: string;
  id?: number;
  imageUrl?: string;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  price?: number;
  quantityAvailable?: number;
  sponsorAds?: Array<SponsorAd>;
  startDate?: string;
  status?: 'COMING_SOON' | 'AVAILABLE' | 'CLOSED';
  title?: string;
  transactions?: Array<SupplierTransaction>;
}
