/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserUpdateRequest {
  email: string;
  firstName: string;
  keycloakId: string;
  lastName: string;
  profilePhotoUrl?: string;
  role: string;
}
