/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface User {
  createdBy?: string;
  createdDate?: string;
  email?: string;
  firstName?: string;
  id?: number;
  keycloakId?: string;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  lastName?: string;
  profilePhotoUrl?: string;
  role?: string;
}
