/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  email?: string;
  firstName?: string;
  id?: string;
  keycloakId?: string;
  lastName?: string;
  profilePhotoUrl?: string;
  role?: string;
}
