package com.dhia.Upvertise.notification;

public enum NotificationStatus {
    SPONSOR_OFFER_CREATED,
    SPONSOR_OFFER_UPDATED,
    SPONSOR_OFFER_DELETED,
    SPONSORSHIP_CREATED,//this happer when an advertiser choose a sponsorOffer
    SPONSORSHIP_UPDATED,
    SPONSORSHIP_DELETED,
    SUPPLIER_OFFER_CREATED,
    SUPPLIER_OFFER_UPDATED,
    SUPPLIER_OFFER_DELETED,
    SUPPLIER_TRANSACTION_CREATED,//this happen when a supplier choose a SupplierOffer
    SUPPLIER_TRANSACTION_UPDATED,
    SUPPLIER_TRANSACTION_DELETED,
    SPONSOR_AD_UPDATED,
    PROVIDERSHIP_CREATED,
    PROVIDERSHIP_UPDATED,
    PROVIDERSHIP_DELETED,
}
