spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/upvertise_DB
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: host.docker.internal:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/Upvertise"
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB




server:
  port: 8088

jwt:
  auth:
    converter:
      resource-id: Upvertise-rest-api
      principle-attribute: preferred_username