/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApplyDiscount$Params {
  transactionId: number;
  numberOfCompletedTransactionNeeded: number;
  discount: number;
}

export function applyDiscount(http: HttpClient, rootUrl: string, params: ApplyDiscount$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, applyDiscount.PATH, 'patch');
  if (params) {
    rb.path('transactionId', params.transactionId, {});
    rb.query('numberOfCompletedTransactionNeeded', params.numberOfCompletedTransactionNeeded, {});
    rb.query('discount', params.discount, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

applyDiscount.PATH = '/supplier-transactions/{transactionId}/apply-discount';
