/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SupplierTransactionMultipartRequest } from '../../models/supplier-transaction-multipart-request';
import { SupplierTransactionResponse } from '../../models/supplier-transaction-response';

export interface UpdateSupplierTransaction$Params {

/**
 * ID of the Supplier Transaction to update
 */
  transactionId: number;
      body?: SupplierTransactionMultipartRequest
}

export function updateSupplierTransaction(http: HttpClient, rootUrl: string, params: UpdateSupplierTransaction$Params, context?: HttpContext): Observable<StrictHttpResponse<SupplierTransactionResponse>> {
  const rb = new RequestBuilder(rootUrl, updateSupplierTransaction.PATH, 'patch');
  if (params) {
    rb.path('transactionId', params.transactionId, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SupplierTransactionResponse>;
    })
  );
}

updateSupplierTransaction.PATH = '/supplier-transactions/update/{transactionId}';
