/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getSignedUploadUrl } from '../fn/cloudinary-controller/get-signed-upload-url';
import { GetSignedUploadUrl$Params } from '../fn/cloudinary-controller/get-signed-upload-url';
import { uploadImage } from '../fn/cloudinary-controller/upload-image';
import { UploadImage$Params } from '../fn/cloudinary-controller/upload-image';

@Injectable({ providedIn: 'root' })
export class CloudinaryControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `uploadImage()` */
  static readonly UploadImagePath = '/cloudinary/upload';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadImage()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  uploadImage$Response(params?: UploadImage$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return uploadImage(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadImage$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  uploadImage(params?: UploadImage$Params, context?: HttpContext): Observable<string> {
    return this.uploadImage$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `getSignedUploadUrl()` */
  static readonly GetSignedUploadUrlPath = '/cloudinary/signed-upload';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSignedUploadUrl()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSignedUploadUrl$Response(params?: GetSignedUploadUrl$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: {
};
}>> {
    return getSignedUploadUrl(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSignedUploadUrl$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSignedUploadUrl(params?: GetSignedUploadUrl$Params, context?: HttpContext): Observable<{
[key: string]: {
};
}> {
    return this.getSignedUploadUrl$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: {
};
}>): {
[key: string]: {
};
} => r.body)
    );
  }

}
