/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SponsorOfferMultipartChooseRequest } from '../../models/sponsor-offer-multipart-choose-request';

export interface ChooseSponsorOffer$Params {
  offerId: number;
      body?: SponsorOfferMultipartChooseRequest
}

export function chooseSponsorOffer(http: HttpClient, rootUrl: string, params: ChooseSponsorOffer$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
  const rb = new RequestBuilder(rootUrl, chooseSponsorOffer.PATH, 'post');
  if (params) {
    rb.path('offerId', params.offerId, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: parseFloat(String((r as HttpResponse<any>).body)) }) as StrictHttpResponse<number>;
    })
  );
}

chooseSponsorOffer.PATH = '/sponsor-offers/chooseSponsorOffer/{offerId}';
