/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageResponseSponsorOfferResponse } from '../../models/page-response-sponsor-offer-response';

export interface GetSponsorOffersByStatus$Params {
  status: string;
  pageable: Pageable;
}

export function getSponsorOffersByStatus(http: HttpClient, rootUrl: string, params: GetSponsorOffersByStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseSponsorOfferResponse>> {
  const rb = new RequestBuilder(rootUrl, getSponsorOffersByStatus.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseSponsorOfferResponse>;
    })
  );
}

getSponsorOffersByStatus.PATH = '/sponsor-offers/sponsorOffersByStatus';
