/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface UpdateChosenSponsorOffer$Params {
  oldOfferId: number;
  newOfferId: number;
}

export function updateChosenSponsorOffer(http: HttpClient, rootUrl: string, params: UpdateChosenSponsorOffer$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, updateChosenSponsorOffer.PATH, 'put');
  if (params) {
    rb.query('oldOfferId', params.oldOfferId, {});
    rb.query('newOfferId', params.newOfferId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

updateChosenSponsorOffer.PATH = '/sponsor-offers/updateSponsorOfferChoice';
