/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SponsorOfferMultipartRequest } from '../../models/sponsor-offer-multipart-request';
import { SponsorOfferResponse } from '../../models/sponsor-offer-response';

export interface UpdateSponsorOffer$Params {
  offerId: number;
      body?: SponsorOfferMultipartRequest
}

export function updateSponsorOffer(http: HttpClient, rootUrl: string, params: UpdateSponsorOffer$Params, context?: HttpContext): Observable<StrictHttpResponse<SponsorOfferResponse>> {
  const rb = new RequestBuilder(rootUrl, updateSponsorOffer.PATH, 'patch');
  if (params) {
    rb.path('offerId', params.offerId, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SponsorOfferResponse>;
    })
  );
}

updateSponsorOffer.PATH = '/sponsor-offers/{offerId}/updateSponsorOffer';
