/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageResponseProvidershipResponse } from '../../models/page-response-providership-response';

export interface GetAllProviderships$Params {
  pageable: Pageable;
}

export function getAllProviderships(http: HttpClient, rootUrl: string, params: GetAllProviderships$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseProvidershipResponse>> {
  const rb = new RequestBuilder(rootUrl, getAllProviderships.PATH, 'get');
  if (params) {
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseProvidershipResponse>;
    })
  );
}

getAllProviderships.PATH = '/providership';
