/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProvidershipResponse } from '../../models/providership-response';

export interface GetProvidershipById$Params {
  providershipId: number;
}

export function getProvidershipById(http: HttpClient, rootUrl: string, params: GetProvidershipById$Params, context?: HttpContext): Observable<StrictHttpResponse<ProvidershipResponse>> {
  const rb = new RequestBuilder(rootUrl, getProvidershipById.PATH, 'get');
  if (params) {
    rb.path('providershipId', params.providershipId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProvidershipResponse>;
    })
  );
}

getProvidershipById.PATH = '/providership/{providershipId}';
