/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProvidershipMultipartRequest } from '../../models/providership-multipart-request';
import { ProvidershipResponse } from '../../models/providership-response';

export interface UpdateProvidership$Params {
  id: number;
      body?: ProvidershipMultipartRequest
}

export function updateProvidership(http: HttpClient, rootUrl: string, params: UpdateProvidership$Params, context?: HttpContext): Observable<StrictHttpResponse<ProvidershipResponse>> {
  const rb = new RequestBuilder(rootUrl, updateProvidership.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProvidershipResponse>;
    })
  );
}

updateProvidership.PATH = '/providership/update/{id}';
