/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseSupplierOfferResponse } from '../../models/page-response-supplier-offer-response';

export interface GetSupplierOffersByStatus$Params {
  status: 'COMING_SOON' | 'AVAILABLE' | 'CLOSED';
  page?: number;
  size?: number;
}

export function getSupplierOffersByStatus(http: HttpClient, rootUrl: string, params: GetSupplierOffersByStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseSupplierOfferResponse>> {
  const rb = new RequestBuilder(rootUrl, getSupplierOffersByStatus.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseSupplierOfferResponse>;
    })
  );
}

getSupplierOffersByStatus.PATH = '/supplier-offers/status';
