/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SupplierTransactionResponse } from '../../models/supplier-transaction-response';

export interface UpdateSupplierChoice$Params {
  transactionId: number;
  newSupplierOfferId: number;
}

export function updateSupplierChoice(http: HttpClient, rootUrl: string, params: UpdateSupplierChoice$Params, context?: HttpContext): Observable<StrictHttpResponse<SupplierTransactionResponse>> {
  const rb = new RequestBuilder(rootUrl, updateSupplierChoice.PATH, 'put');
  if (params) {
    rb.path('transactionId', params.transactionId, {});
    rb.path('newSupplierOfferId', params.newSupplierOfferId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SupplierTransactionResponse>;
    })
  );
}

updateSupplierChoice.PATH = '/supplier-offers/{transactionId}/update-choice/{newSupplierOfferId}';
