/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SupplierOfferRequest } from '../../models/supplier-offer-request';
import { SupplierOfferResponse } from '../../models/supplier-offer-response';

export interface UpdateSupplierOffer$Params {
  id: number;
      body?: {
'request': SupplierOfferRequest;
'newImage': Blob;
}
}

export function updateSupplierOffer(http: HttpClient, rootUrl: string, params: UpdateSupplierOffer$Params, context?: HttpContext): Observable<StrictHttpResponse<SupplierOfferResponse>> {
  const rb = new RequestBuilder(rootUrl, updateSupplierOffer.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SupplierOfferResponse>;
    })
  );
}

updateSupplierOffer.PATH = '/supplier-offers/update/{id}';
