export interface Notification {
  status?: 'SPONSOR_OFFER_CREATED' |
  'SPONSOR_OFFER_UPDATED'|
  'SPONSOR_OFFER_DELETED'|
  'SPONSORSHIP_CREATED'|
  'SPONSORSHIP_UPDATED'|
  'SPONSORSHIP_DELETED'|
  'SUPPLIER_OFFER_CREATED'|
  'SUPPLIER_OFFER_UPDATED'|
  'SUPPLIER_OFFER_DELETED'|
  'SUPPLIER_TRANSACTION_CREATED'|
  'SUPPLIER_TRANSACTION_UPDATED'|
  'SUPPLIER_TRANSACTION_DELETED'|
  'SPONSOR_AD_UPDATED'|
    'PROVIDERSHIP_CREATED'|
  'PROVIDERSHIP_UPDATED'|
  'PROVIDERSHIP_DELETED';
  message?: string;
}
