spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  kafka:
    bootstrap-servers: host.docker.internal:9092
    consumer:
      group-id: email-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        retry.backoff.ms: 1000
        retries: 5
        security.protocol: PLAINTEXT

  mail:
      host: smtp.gmail.com
      port: 587
      username: "meddhiarejeb22@gmail.com"
      password: "lhiu jfno xidt dizq"
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true


server:
  port: 8081  # Change this to avoid port conflicts
app:
  backend-url: http://localhost:8088


